import {
  BUBBLE_COOLDOWN_FRAMES,
  BUBBLE_DISPLAY_FRAMES,
  DEFAULT_ANIMATION_SPEED,
  DEFAULT_BUBBLE_CHANCE,
  DEFAULT_FOLLOW_DISTANCE,
  DEFAULT_IDLE_THRESHOLD_MS,
  DEFAULT_OPACITY,
  DEFAULT_ROTATION_AMOUNT,
  DEFAULT_SCALE,
  DEFAULT_SPEED,
  DEFAULT_VOLUME,
  DEFAULT_Z_INDEX,
  FREERUN_CHANCE,
  FREERUN_DURATION,
} from "./constants";
import type { OnekoProps } from "./types";

export const ONEKO_DEFAULTS = {
  paused: false,
  followCursor: true,
  sleepEnabled: true,
  bubblePlacement: "auto" as NonNullable<OnekoProps["bubblePlacement"]>,
  bubbleScale: 1,
  soundBasePath: "/cat-sounds",
  storageKey: "oneko",
  zoneAttractionChance: 0.3,
  zoneAttractionDuration: 4000,
  skin: "classic" as NonNullable<OnekoProps["skin"]>,
  persistPosition: true,
  reducedMotion: "hide" as NonNullable<OnekoProps["reducedMotion"]>,
  zIndex: DEFAULT_Z_INDEX,
  speed: DEFAULT_SPEED,
  scale: DEFAULT_SCALE,
  opacity: DEFAULT_OPACITY,
  rotationAmount: DEFAULT_ROTATION_AMOUNT,
  idleThreshold: DEFAULT_IDLE_THRESHOLD_MS,
  meow: false,
  freerunChance: FREERUN_CHANCE,
  freerunDuration: FREERUN_DURATION,
  bubbleEnabled: true,
  bubbleDisplayFrames: BUBBLE_DISPLAY_FRAMES,
  bubbleCooldown: BUBBLE_COOLDOWN_FRAMES,
  hueRotate: 0,
  bubbleChance: DEFAULT_BUBBLE_CHANCE,
  followDistance: DEFAULT_FOLLOW_DISTANCE,
  animationSpeed: DEFAULT_ANIMATION_SPEED,
  bubbleText: "",
  volume: DEFAULT_VOLUME,
  laserPointer: false,
};
